// =========================================================
// INITIAL ISLAMABAD TECH EVENTS DATASET
// Pre-populated seed dataset for local fallback & instant preview
// =========================================================

export const INITIAL_EVENTS = [
  {
    id: "evt-101",
    title: "Islamabad AI Hackathon 2026",
    category: "Hackathon",
    format: "In-Person",
    sector: "FAST-NUCES (H-11)",
    city: "Islamabad",
    organizer_name: "Islamabad AI Society",
    is_official: true,
    start_date: "2026-08-25",
    deadline: "2026-08-20",
    description: "A premier 36-hour generative AI and large language model hackathon bringing together top developers, university students, and AI researchers from Islamabad & Rawalpindi. Build real-world intelligent software solutions and pitch directly to local tech venture funds.",
    agenda: "Day 1: Keynote & Problem Statements • Day 2: 24-hr Coding Sprint & Mentorship • Day 3: Top 10 Pitches & Award Ceremony.",
    prize_pool: "PKR 300,000 + Cloud Credits",
    fee: "Free",
    banner_url: "assets/event-ai-hackathon.png",
    registration_url: "https://fast.edu.pk/ai-hackathon",
    created_at: "2026-08-01T10:00:00Z"
  },
  {
    id: "evt-102",
    title: "City Code Sprint 2026",
    category: "Coding Competition",
    format: "In-Person",
    sector: "NUST (H-12)",
    city: "Islamabad",
    organizer_name: "City Innovation Lab",
    is_official: true,
    start_date: "2026-09-02",
    deadline: "2026-08-28",
    description: "ACM-style high-speed competitive programming challenge. Solvers get 8 algorithmic problems ranging from dynamic programming, graph theory, to network flow. Open to individual coders and university teams.",
    agenda: "09:00 AM Practice Round • 11:30 AM Official Contest (4 Hours) • 04:00 PM Scoreboard Unfreeze & Winners.",
    prize_pool: "PKR 150,000",
    fee: "Free",
    banner_url: "assets/event-code-sprint.png",
    registration_url: "https://nust.edu.pk/code-sprint",
    created_at: "2026-08-02T12:00:00Z"
  },
  {
    id: "evt-103",
    title: "Full-Stack Modern Frontend Systems",
    category: "Workshop",
    format: "Hybrid",
    sector: "NSU (I-9)",
    city: "Islamabad",
    organizer_name: "Developer Guild Islamabad",
    is_official: true,
    start_date: "2026-08-18",
    deadline: "2026-08-16",
    description: "Hands-on intensive masterclass covering JavaScript modern standard, high-performance UI architecture, design tokens, micro-frontends, and seamless state management. Includes live building project.",
    agenda: "Module 1: Modular JS Architecture • Module 2: Design Systems & CSS Tokens • Module 3: Live API Integration & Deployment.",
    prize_pool: "Certificate + Swag Pack",
    fee: "PKR 1,000",
    banner_url: "assets/event-frontend-workshop.png",
    registration_url: "https://devguild.isb.pk/workshop",
    created_at: "2026-08-03T09:00:00Z"
  },
  {
    id: "evt-104",
    title: "Islamabad Junior Dev Hiring Day",
    category: "Career Program",
    format: "In-Person",
    sector: "STP (I-9)",
    city: "Islamabad",
    organizer_name: "City Employers Network",
    is_official: true,
    start_date: "2026-09-10",
    deadline: "2026-09-05",
    description: "On-site resume evaluation, technical code screening, and rapid 1-on-1 interviews with 20+ software engineering companies located in Islamabad Software Technology Park.",
    agenda: "10:00 AM Registration & Employer Stalls • 01:00 PM Technical Code Screening • 03:30 PM Fast-Track Interviews.",
    prize_pool: "Job & Internship Offers",
    fee: "Free",
    banner_url: "assets/event-hiring-day.png",
    registration_url: "https://isbtech.pk/hiring-day",
    created_at: "2026-08-04T11:00:00Z"
  },
  {
    id: "evt-105",
    title: "Open Tech Data & GovTech Challenge",
    category: "Hackathon",
    format: "Online",
    sector: "Online",
    city: "Islamabad",
    organizer_name: "Civic Tech Pakistan",
    is_official: false,
    start_date: "2026-09-15",
    deadline: "2026-09-12",
    description: "Utilize public government datasets to build open-source tools for Islamabad urban planning, traffic optimization, emergency services, and citizen engagement.",
    agenda: "Dataset Release • Virtual Mentorship Hours • Final Repository Submission & Video Demo.",
    prize_pool: "PKR 200,000",
    fee: "Free",
    banner_url: "assets/event-open-data.png",
    registration_url: "https://civictech.pk/open-data",
    created_at: "2026-08-05T08:00:00Z"
  },
  {
    id: "evt-106",
    title: "Islamabad Tech Fellowship & Bootcamp Forum",
    category: "Bootcamp",
    format: "In-Person",
    sector: "COMSATS (Park Rd)",
    city: "Islamabad",
    organizer_name: "Global Talent Network",
    is_official: true,
    start_date: "2026-09-22",
    deadline: "2026-09-18",
    description: "Launch event for a 12-week fully funded intensive bootcamp in Cloud Computing, DevOps, and Backend Systems Architecture for selected students in Islamabad.",
    agenda: "Program Orientation • Curriculum Breakdown • Entrance Assessment Guidelines.",
    prize_pool: "100% Fully Funded",
    fee: "Free",
    banner_url: "assets/event-scholarship-forum.png",
    registration_url: "https://comsats.edu.pk/fellowship",
    created_at: "2026-08-05T09:30:00Z"
  }
];
